export const provincesList = [
    { key: "01", label: "Araba/Álava" },
    { key: "02", label: "Albacete" },
    { key: "03", label: "Alacant/Alicante" },
    { key: "04", label: "Almería" },
    { key: "05", label: "Ávila" },
    { key: "06", label: "Badajoz" },
    { key: "07", label: "Illes Balears" },
    { key: "08", label: "Barcelona" },
    { key: "09", label: "Burgos" },
    { key: "10", label: "Cáceres" },
    { key: "11", label: "Cádiz" },
    { key: "12", label: "Castelló/Castellón" },
    { key: "13", label: "Ciudad Real" },
    { key: "14", label: "Córdoba" },
    { key: "15", label: "A Coruña" },
    { key: "16", label: "Cuenca" },
    { key: "17", label: "Girona" },
    { key: "18", label: "Granada" },
    { key: "19", label: "Guadalajara" },
    { key: "20", label: "Gipuzkoa" },
    { key: "21", label: "Huelva" },
    { key: "22", label: "Huesca" },
    { key: "23", label: "Jaén" },
    { key: "24", label: "León" },
    { key: "25", label: "Lleida" },
    { key: "26", label: "La Rioja" },
    { key: "27", label: "Lugo" },
    { key: "28", label: "Madrid" },
    { key: "29", label: "Málaga" },
    { key: "30", label: "Murcia" },
    { key: "31", label: "Navarra" },
    { key: "32", label: "Ourense" },
    { key: "33", label: "Asturias" },
    { key: "34", label: "Palencia" },
    { key: "35", label: "Las Palmas" },
    { key: "36", label: "Pontevedra" },
    { key: "37", label: "Salamanca" },
    { key: "38", label: "Santa Cruz de Tenerife" },
    { key: "39", label: "Cantabria" },
    { key: "40", label: "Segovia" },
    { key: "41", label: "Sevilla" },
    { key: "42", label: "Soria" },
    { key: "43", label: "Tarragona" },
    { key: "44", label: "Teruel" },
    { key: "45", label: "Toledo" },
    { key: "46", label: "València/Valencia" },
    { key: "47", label: "Valladolid" },
    { key: "48", label: "Bizkaia" },
    { key: "49", label: "Zamora" },
    { key: "50", label: "Zaragoza" },
    { key: "51", label: "Ceuta" },
    { key: "52", label: "Melilla" }]