
 
    export const GETALL_MUNICIPALITIES_REQUEST = 'GETALL_MUNICIPALITIES_REQUEST';
    export const GETALL_MUNICIPALITIES_SUCCESS = 'USERS_GETALL_MUNICIPALITIES_SUCCESS';
    export const GETALL_MUNICIPALITIES_FAILURE = 'USERS_GETALL_MUNICIPALITIES_FAILURE';
