
    export const USERS_REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
    export const USERS_REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
    export const USERS_REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

    export const USERS_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
    export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
    export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

    export const USERS_SAVE_SEARCH_REQUEST = 'USERS_SAVE_SEARCH_REQUEST';
    export const USERS_SAVE_SEARCH_SUCCESS = 'USERS_SAVE_SEARCH_SUCCESS';
    export const USERS_SAVE_SEARCH_FAILURE = 'USERS_SAVE_SEARCH_FAILURE';

    export const USERS_REMOVE_SEARCH_REQUEST = 'USERS_REMOVE_SEARCH_REQUEST';
    export const USERS_REMOVE_SEARCH_SUCCESS = 'USERS_REMOVE_SEARCH_SUCCESS';
    export const USERS_REMOVE_SEARCH_FAILURE = 'USERS_REMOVE_SEARCH_FAILURE';

    export const USERS_GET_SEARCHS_REQUEST = 'USERS_GET_SEARCH_REQUEST';
    export const USERS_GET_SEARCHS_SUCCESS = 'USERS_GET_SEARCH_SUCCESS';
    export const USERS_GET_SEARCHS_FAILURE = 'USERS_GET_SEARCH_FAILURE';


    
    export const USERS_LOGOUT = 'USERS_LOGOUT';
