
    export const USERS_REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
    export const USERS_REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
    export const USERS_REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

    export const USERS_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
    export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
    export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
    
    export const USERS_LOGOUT = 'USERS_LOGOUT';
