
 
    export const GET_WEATHER_CONDITON_REQUEST = 'GET_WEATHER_CONDITON_REQUEST';
    export const GET_WEATHER_CONDITON_SUCCESS = 'GET_WEATHER_CONDITON_SUCCESS';
    export const GET_WEATHER_CONDITON_FAILURE = 'GET_WEATHER_CONDITON_FAILURE';
